import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, DM_Sans } from "next/font/google";
import "./globals.css";
import { ViewTransition } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const DMSans = DM_Sans({
  variable: "--font-DM-Sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My own Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${DMSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="bg-home bg-no-repeat bg-cover">
          <ViewTransition>{children}</ViewTransition>
        </div>
      </body>
    </html>
  );
}
