import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Montserrat,
  DM_Sans,
  Tomorrow,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const DMSans = DM_Sans({
  variable: "--font-DM-Sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const tomorrow = Tomorrow({
  variable: "--font-Tomorrow",
  subsets: ["latin"],
  weight: "100",
});

export const metadata: Metadata = {
  title: "My own Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${DMSans.variable} ${tomorrow.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
